version: "2"
linters:
  enable:
    - misspell
    - revive
  disable:
    - errcheck
    - govet
    - staticcheck
    - unused
  settings:
    revive:
      rules:
        - name: exported
          arguments:
            - disableStutteringCheck
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  settings:
    goimports:
      local-prefixes:
        - github.com/kubevela/pkg
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
