run:
  timeout: 10m

linters:
  enable:
    - misspell
    - revive
  fast: true

linters-settings:
  goimports:
    local-prefixes: github.com/kubevela/pkg
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck

issues:
  include:
    - EXC0012  # EXC0012 revive: Annoying issue about not having a comment. The rare codebase has such comments
    - EXC0014  # EXC0014 revive: Annoying issue about not having a comment. The rare codebase has such comments